<?php
/**
 * @file
 * Client-side data space.
 */

/**
 * Implements hook_menu().
 */
function datalayer_menu() {
  $items['admin/config/search/datalayer'] = array(
    'title' => 'Data Layer',
    'description' => 'Output page meta data for client-side use.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('datalayer_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'datalayer.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_preprocess_HOOK().
 * 
 * Outputs meta data details of the page.
 */
function datalayer_preprocess_html(&$variables) {
  $output_data = array();

  // Add details about the page.
  if (variable_get('datalayer_add_page_meta', TRUE)) {

    $type = FALSE;
    $obj = _datalayer_menu_get_any_object($type);
    if (is_object($obj) && $type) {
      // Populate entity properties and values.
      $output_data = _datalayer_get_entity_data($obj, $type);
    }

    // Merge data from datalayer_add_dl() (includes defaults) and entity values.
    $output_data = array_merge($output_data, datalayer_add_dl());

    // Allow modules to alter data with hook_datalayer_dl_alter().
    drupal_alter('datalayer_dl', $output_data);

    // Output page meta data as an array of objects.
    $output = !empty($output_data) ? drupal_json_encode($output_data) : '';

    $render = array(
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => 'dataLayer = [' . $output . '];',
      '#attributes' => array(
        'type' => 'text/javascript',
      ),
    );
    drupal_add_html_head($render, 'datalayer_meta');

    // Include data-layer-helper library.
    if (variable_get('datalayer_lib_helper', TRUE)) {
      if (function_exists('libraries_load') && libraries_load('data-layer-helper')) {
        // You have Libraries 2.0 and some other module registered this.
        // The test above will cause the load.
      }
      else {
        $path = libraries_get_path('data-layer-helper');
        if (!empty($path) && file_exists($path . '/data-layer-helper.js')) {
          drupal_add_js($path . '/data-layer-helper.js');
        }
      }
    }

  }
}


/**
 * Collects up meta data for output.
 * 
 * @return {array}
 *   Array of all candidate entity properties.
 */
function _datalayer_collect_meta_properties() {
  // Avoid duplicate builds.
  $properties = &drupal_static(__FUNCTION__);
  if (!isset($properties)) {

    $properties = array('entityType', 'bundle');
    foreach (module_implements('datalayer_meta') as $module) {
      // Call modules implementing datalayer_meta() and combine results.
      $properties = array_merge($properties,
        module_invoke($module, 'datalayer_meta')
      );
    }
    drupal_alter('datalayer_meta', $properties);
  }

  return $properties;
}


/**
 * Implements hook_datalayer_meta().
 * 
 * Defines default meta data.
 */
function datalayer_datalayer_meta() {
  return array(
    'title',
    'language',
    'nid',
    'tnid',
    'tid',
    'vid',
    'name',
    'uid',
    'created',
    'status',
  );
}


/**
 * Collect entity data for output and altering.
 *
 * @param {object} $obj
 *   Entity object of the page menu callback.
 * @param {string} $type
 *   String representing entitie's type.
 *
 * @return
 *   Array of all properties and values for output of page entity.
 */
function _datalayer_get_entity_data($obj, $type) {
  $output_data = &drupal_static(__FUNCTION__);
  if (empty($output_data)) {

    // Explicit additions.
    $output_data['entityType'] = $type;
    $output_data['entityBundle'] = (isset($obj->type)) ? $obj->type : FALSE;

    // Output various entity properties. Allow additions/alterations.
    // NOTE: Properties mean different things on different entity types.
    $properties = _datalayer_collect_meta_properties();
    $selected_properties = array_filter(variable_get('datalayer_entity_meta', array()));

    // Build meta output...
    // Honor selective output configuration.
    if (empty($selected_properties)) {
      // Include all in output, only entity valid.
      foreach ($properties as $p) {
        if (isset($obj->$p)) {
          $output_data['entity' . ucfirst($p)] = $obj->$p;
        }
      }
    }
    else {
      // Include only entity valid and config selected.
      foreach ($properties as $p) {
        if (isset($obj->$p) && $selected_properties[$p]) {
          $output_data['entity' . ucfirst($p)] = $obj->$p;
        }
      }
    }

    // Output term data.
    if (variable_get('datalayer_output_terms', TRUE)) {
      $selected_vocabs = array_filter(variable_get('datalayer_vocabs', array()));

      if ($type == 'taxonomy_term') {
        $output_data['entityTaxonomy'] = array($obj->vocabulary_machine_name => $obj->tid);
      }
      else {

        // Meta data on content.
        if ($taxonomy = _datalayer_get_entity_terms($type, $obj->type, $obj)) {
          // Limit configured vocabs.
          if (empty($selected_vocabs)) {
            $output_data['entityTaxonomy'] = $taxonomy;
          }
          else {
            foreach ($taxonomy as $vocab => $terms) {
              if (isset($selected_vocabs[$vocab])) {
                $output_data['entityTaxonomy'][$vocab] = $terms;
              }
            }
          }
        }

      }
    }

  }

  return $output_data;
}


/**
 * Allow adding to the data layer output easy on the fly.
 * Think of this as a drupal_add_js().
 *
 * @param {array} $data
 *   An array of dataLayer data keyed by variable name.
 * @param {boolean} $overwrite
 *   If data should overwrite existing dataLayer vars of same name. Defaults FALSE.
 *
 * @return {array}
 *   All data layer data added thus far.
 */
function datalayer_add_dl($data = array(), $overwrite = FALSE) {
  $output_data = &drupal_static(__FUNCTION__, _datalayer_dl_defaults());

  // If we've been given data, add it to the output.
  if (!empty($data)) {
    if ($overwrite) {
      $output_data = array_merge($output_data, $data);
    }
    else {
      $output_data += $data;
    }
  }

  return $output_data;
}


/**
 * Defines Drupal-wide data layer defaults.
 */
function _datalayer_dl_defaults() {
  global $language, $user;

  return array(
    'drupalLanguage' => $language->language,
    'userStatus' => $user->uid > 0 ? 'authenticated' : 'anonymous',
    'userUid' => $user->uid,
  );
}


/**
 * Utility function to agnosticly get the current menu object.
 * Structured like menu_get_object(), but the passed type will be set for you.
 *
 * @param {string} (reference) $return_type
 *   Pass in a type variable by reference for later use.
 *
 * return {object}
 *   Entity object of current menu callback page.
 */
function _datalayer_menu_get_any_object(&$return_type) {
  // Figure out how this entity is loaded.
  $type = FALSE;
  $item = menu_get_item();
  $vals = array_values($item['load_functions']);
  $load_function = $vals[0];
  $arg_position = array_search($load_function, $item['load_functions']);

  // Compare to entity types.
  $entity_info = entity_get_info();
  foreach ($entity_info as $i => $e) {
    if ($e['load hook'] == $load_function) {
      $type = $i;
    }
  }

  // Many happy returns.
  if ($type && $obj = menu_get_object($type, $arg_position)) {
    if (is_object($obj)) {
      $return_type = $type;
      return $obj;
    }
    else {
      return FALSE;
    }
  }
  else {
    return FALSE;
  }
}


/**
 * Utility function to fetch all taxonomy terms from an entity.
 * All fields of field type "taxonomy_term_reference" will be included.
 * Idea found at https://api.drupal.org/comment/50393#comment-50393
 *
 * @param {string} $entity_type
 *   What type of entity.
 * @param {string} $bundle
 *   What bundle within entity type.
 * @param {object} $entity
 *   Actual entity object to process.
 *
 * @return array
 *   Array with tids of entity.
 */
function _datalayer_get_entity_terms($entity_type, $bundle, $entity) {
  $terms = array();

  // Use very lightweight field info list to find relevant fields.
  foreach (field_info_field_map() as $field_name => $field_info) {
    if ($field_info['type'] <> "taxonomy_term_reference") {
      continue;
    }
    if (array_key_exists($entity_type, $field_info['bundles'])) {
      if (in_array($bundle, $field_info['bundles'][$entity_type])) {
        if (isset($entity->{$field_name})) {
          // Collect terms from fields for return.
          $values = field_get_items($entity_type, $entity, $field_name);
          foreach ((array) $values as $term_array) {
            // Limit to existant tids.
            if (isset($term_array['tid']) && $term = taxonomy_term_load($term_array['tid'])) {
              $terms[$term->vocabulary_machine_name][$term->tid] = $term->name;
            }
          }
        }
      }
    }
  }

  return $terms;
}
